import 'package:flutter/material.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/Generated750pointsWidget.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedButtonWidget7.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedStatusBarWidget2.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedWidget10.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedRectangle25Widget2.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedEllipse9Widget2.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedButtonWidget5.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedIcontogglestar_outline_24pxWidget4.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedEllipse11Widget2.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedRectangle24Widget2.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedIconsocialperson_outline_24pxWidget2.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedEllipse10Widget2.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedRectangle23Widget2.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedPointsWidget.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedRectangleWidget2.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedUnionWidget1.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedButtonWidget8.dart';
import 'package:flutterapp/machacksapp/generatedrewardswidget/generated/GeneratedButtonWidget6.dart';

/* Frame Rewards
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedRewardsWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget2(),
              ),
              Positioned(
                left: 192.0,
                top: 1130.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 220.0,
                child: GeneratedRectangle25Widget2(),
              ),
              Positioned(
                left: 192.0,
                top: 811.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 310.0,
                child: GeneratedRectangle23Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 1040.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 310.0,
                child: GeneratedRectangle24Widget2(),
              ),
              Positioned(
                left: 16.0,
                top: 1382.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedButtonWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget2(),
              ),
              Positioned(
                left: 21.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 12.207107543945312,
                height: 11.353558540344238,
                child: GeneratedUnionWidget1(),
              ),
              Positioned(
                left: 24.0,
                top: 87.0,
                right: null,
                bottom: null,
                width: 331.0,
                height: 71.0,
                child: Generated750pointsWidget(),
              ),
              Positioned(
                left: 22.0,
                top: 199.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 87.0,
                child: GeneratedButtonWidget6(),
              ),
              Positioned(
                left: 21.0,
                top: 308.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 87.0,
                child: GeneratedButtonWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.9146666666666666;

                  final double height =
                      constraints.maxHeight * 0.10714285714285714;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666666666666666,
                        y: constraints.maxHeight * 0.5135467980295566,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedButtonWidget8(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 53.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 74.0,
                child: GeneratedPointsWidget(),
              ),
              Positioned(
                left: 261.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse11Widget2(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.042666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 16.0;

                  double percentHeight = 0.019704433497536946;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 16.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7386666666666667,
                        translateY: constraints.maxHeight * 0.75,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedIconsocialperson_outline_24pxWidget2())
                  ]);
                }),
              ),
              Positioned(
                left: 171.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse10Widget2(),
              ),
              Positioned(
                left: 189.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 38.0,
                child: GeneratedWidget10(),
              ),
              Positioned(
                left: 81.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse9Widget2(),
              ),
              Positioned(
                left: 94.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcontogglestar_outline_24pxWidget4(),
              )
            ]),
      ),
    ));
  }
}
