import 'package:flutter/material.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget2/generated/GeneratedEllipse1Widget2.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget2/generated/GeneratedRectangleWidget12.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget2/generated/GeneratedStatusBarWidget7.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget2/generated/GeneratedEllipse2Widget2.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget2/generated/GeneratedImage2Widget.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget2/generated/GeneratedButtonWidget15.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget2/generated/GeneratedEllipse3Widget2.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget2/generated/GeneratedFrame1Widget3.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget2/generated/GeneratedRectangleWidget11.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget2/generated/GeneratedGoogleWellnessisaplacetogrowWidget.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget2/generated/GeneratedRectangleWidget13.dart';

/* Frame Intro Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntroPageWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget11(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget13(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget7(),
              ),
              Positioned(
                left: 81.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 51.0,
                child: GeneratedFrame1Widget3(),
              ),
              Positioned(
                left: 50.0,
                top: 77.0,
                right: null,
                bottom: null,
                width: 283.0,
                height: 218.0,
                child: GeneratedGoogleWellnessisaplacetogrowWidget(),
              ),
              Positioned(
                left: 141.0,
                top: 602.0,
                right: 132.0,
                bottom: null,
                width: null,
                height: 40.0,
                child: GeneratedButtonWidget15(),
              ),
              Positioned(
                left: 147.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse1Widget2(),
              ),
              Positioned(
                left: 187.0,
                top: 577.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse2Widget2(),
              ),
              Positioned(
                left: 224.5,
                top: 577.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse3Widget2(),
              ),
              Positioned(
                left: 70.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 122.0,
                height: 161.0,
                child: GeneratedImage2Widget(),
              )
            ]),
      ),
    ));
  }
}
