import 'package:flutter/material.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget2/generated/GeneratedFrame1Widget5.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget2/generated/GeneratedComponentWidget.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget2/generated/GeneratedRectangle2Widget18.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget2/generated/GeneratedStatusBarWidget9.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget2/generated/GeneratedComponentWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget2/generated/GeneratedNEXTWidget1.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget2/generated/GeneratedCreateyourWellnessAccountWidget.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget2/generated/GeneratedRectangleWidget15.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget15(),
              ),
              Positioned(
                left: 13.0,
                top: 429.0,
                right: 19.0,
                bottom: null,
                width: null,
                height: 52.0,
                child: GeneratedComponentWidget(),
              ),
              Positioned(
                left: 12.0,
                top: 354.0,
                right: 20.0,
                bottom: null,
                width: null,
                height: 52.0,
                child: GeneratedComponentWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget9(),
              ),
              Positioned(
                left: 81.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 51.0,
                child: GeneratedFrame1Widget5(),
              ),
              Positioned(
                left: 48.0,
                top: 115.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 208.0,
                child: GeneratedCreateyourWellnessAccountWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.9146666666666666;
                  double scaleX = (constraints.maxWidth * percentWidth) / 343.0;

                  double percentHeight = 0.06403940886699508;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 52.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.034666666666666665,
                        translateY: constraints.maxHeight * 0.6958128078817734,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedRectangle2Widget18())
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width = constraints.maxWidth * 0.136;

                  final double height =
                      constraints.maxHeight * 0.034482758620689655;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.43733333333333335,
                        y: constraints.maxHeight * 0.7130541871921182,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedNEXTWidget1(),
                        ))
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
