import 'package:flutter/material.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget/generated/GeneratedMindfulnessstartswithyouWidget.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget/generated/GeneratedStatusBarWidget4.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget/generated/GeneratedRectangleWidget4.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget/generated/GeneratedLoginWithGoogleWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget/generated/GeneratedGoogleWellnessWidget.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget/generated/GeneratedButtonWidget12.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget/generated/GeneratedFrame1Widget.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget/generated/GeneratedLoginWithWellnessAccountWidget.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget4(),
              ),
              Positioned(
                left: 119.0,
                top: null,
                right: null,
                bottom: null,
                width: 133.0,
                height: 20.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 237.00,
                    z: 0,
                    child: GeneratedLoginWithGoogleWidget()),
              ),
              Positioned(
                left: 16.0,
                top: 564.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 52.0,
                child: GeneratedButtonWidget12(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget4(),
              ),
              Positioned(
                left: 81.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 51.0,
                child: GeneratedFrame1Widget(),
              ),
              Positioned(
                left: 59.0,
                top: 124.0,
                right: null,
                bottom: null,
                width: 293.0,
                height: 211.0,
                child: GeneratedGoogleWellnessWidget(),
              ),
              Positioned(
                left: 55.0,
                top: 322.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 208.0,
                child: GeneratedMindfulnessstartswithyouWidget(),
              ),
              Positioned(
                left: 83.0,
                top: null,
                right: null,
                bottom: null,
                width: 205.0,
                height: 20.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 272.00,
                    z: 0,
                    child: GeneratedLoginWithWellnessAccountWidget()),
              )
            ]),
      ),
    ));
  }
}
