import 'package:flutter/material.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedIconsocialperson_outline_24pxWidget3.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedWidget11.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedEllipse10Widget3.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedIcontogglestar_outline_24pxWidget6.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedRecomendedResourcesWidget.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedRectangleWidget3.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedEllipse9Widget3.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedStatusBarWidget3.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedRectangle25Widget3.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedButtonWidget11.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedEllipse11Widget3.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedRectangle24Widget3.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedButtonWidget10.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedButtonWidget9.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedUnionWidget2.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/GeneratedRectangle23Widget3.dart';
import 'package:flutterapp/machacksapp/generatedresourceswidget/generated/Generated20minutefullbodyworkoutforbeginnersnoequipmentWidget.dart';

/* Frame Resources
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedResourcesWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget3(),
              ),
              Positioned(
                left: 192.0,
                top: 1130.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 220.0,
                child: GeneratedRectangle25Widget3(),
              ),
              Positioned(
                left: 192.0,
                top: 811.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 310.0,
                child: GeneratedRectangle23Widget3(),
              ),
              Positioned(
                left: 16.0,
                top: 1040.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 310.0,
                child: GeneratedRectangle24Widget3(),
              ),
              Positioned(
                left: 16.0,
                top: 1382.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedButtonWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget3(),
              ),
              Positioned(
                left: 21.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 12.207107543945312,
                height: 11.353558540344238,
                child: GeneratedUnionWidget2(),
              ),
              Positioned(
                left: 55.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 71.0,
                child: GeneratedRecomendedResourcesWidget(),
              ),
              Positioned(
                left: 15.0,
                top: 118.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 212.0,
                child: GeneratedButtonWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.4053333333333333;

                  final double height =
                      constraints.maxHeight * 0.08004926108374384;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.5386666666666666,
                        y: constraints.maxHeight * 0.2413793103448276,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child:
                              Generated20minutefullbodyworkoutforbeginnersnoequipmentWidget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 15.0,
                top: 352.0,
                right: null,
                bottom: null,
                width: 341.0,
                height: 212.0,
                child: GeneratedButtonWidget11(),
              ),
              Positioned(
                left: 261.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse11Widget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.042666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 16.0;

                  double percentHeight = 0.019704433497536946;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 16.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.7413333333333333,
                        translateY: constraints.maxHeight * 0.75,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedIconsocialperson_outline_24pxWidget3())
                  ]);
                }),
              ),
              Positioned(
                left: 171.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse10Widget3(),
              ),
              Positioned(
                left: 189.0,
                top: 600.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 38.0,
                child: GeneratedWidget11(),
              ),
              Positioned(
                left: 81.0,
                top: 594.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse9Widget3(),
              ),
              Positioned(
                left: 94.0,
                top: 605.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcontogglestar_outline_24pxWidget6(),
              )
            ]),
      ),
    ));
  }
}
