import 'package:flutter/material.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse14Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedWidget8.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse19Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/Generated3Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse11Widget1.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedRectangle24Widget1.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse16Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedWidget5.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedWidget6.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedRectangleWidget1.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/Generated9Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedWidget2.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse18Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedRectangle25Widget1.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/Generated1Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse13Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/Generated0Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedWidget9.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedScaleof110Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedIconsocialperson_outline_24pxWidget1.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedNumberofHealthyMealsthisweekWidget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse12Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedPleasefilloutyourdailyquestionnaireWidget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedLevelofStressyoufeltthisweek1to10Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedRectangle5Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedRectangle23Widget1.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedRectangle7Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedIcontogglestar_outline_24pxWidget2.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedStatusBarWidget1.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedWidget3.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedWidget7.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedWidget1.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse17Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse9Widget1.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse20Widget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedHoursofphysicalactivitythisweekWidget.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedWidget4.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedButtonWidget3.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedButtonWidget4.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse10Widget1.dart';
import 'package:flutterapp/machacksapp/generatedquestionnarewidget/generated/GeneratedEllipse15Widget.dart';

/* Frame Questionnare
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedQuestionnareWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget1(),
              ),
              Positioned(
                left: 192.0,
                top: 1130.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 220.0,
                child: GeneratedRectangle25Widget1(),
              ),
              Positioned(
                left: 192.0,
                top: 811.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 310.0,
                child: GeneratedRectangle23Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 1040.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 310.0,
                child: GeneratedRectangle24Widget1(),
              ),
              Positioned(
                left: 16.0,
                top: 1382.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedButtonWidget3(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget1(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8853333333333333;

                  final double height =
                      constraints.maxHeight * 0.07512315270935961;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.056,
                        y: constraints.maxHeight * 0.20566502463054187,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle5Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8853333333333333;

                  final double height =
                      constraints.maxHeight * 0.07512315270935961;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666666666666666,
                        y: constraints.maxHeight * 0.31157635467980294,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle6Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8853333333333333;

                  final double height =
                      constraints.maxHeight * 0.07512315270935961;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.058666666666666666,
                        y: constraints.maxHeight * 0.4248768472906404,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle7Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 216.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 25.0,
                child: GeneratedEllipse13Widget(),
              ),
              Positioned(
                left: 305.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 25.0,
                child: GeneratedEllipse14Widget(),
              ),
              Positioned(
                left: 218.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 25.0,
                child: GeneratedEllipse15Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  final double width =
                      constraints.maxWidth * 0.8853333333333333;

                  final double height =
                      constraints.maxHeight * 0.07512315270935961;

                  return Stack(children: [
                    TransformHelper.translate(
                        x: constraints.maxWidth * 0.042666666666666665,
                        y: constraints.maxHeight * 0.5246305418719212,
                        z: 0,
                        child: Container(
                          width: width,
                          height: height,
                          child: GeneratedRectangle8Widget(),
                        ))
                  ]);
                }),
              ),
              Positioned(
                left: 272.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 31.0,
                child: Generated9Widget(),
              ),
              Positioned(
                left: 218.0,
                top: 445.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 25.0,
                child: GeneratedEllipse16Widget(),
              ),
              Positioned(
                left: 210.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 43.0,
                child: GeneratedWidget1(),
              ),
              Positioned(
                left: 309.0,
                top: 444.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 25.0,
                child: GeneratedEllipse17Widget(),
              ),
              Positioned(
                left: 39.0,
                top: 71.0,
                right: null,
                bottom: null,
                width: 287.0,
                height: 71.0,
                child: GeneratedPleasefilloutyourdailyquestionnaireWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 175.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 71.0,
                child: GeneratedHoursofphysicalactivitythisweekWidget(),
              ),
              Positioned(
                left: 269.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 31.0,
                child: Generated0Widget(),
              ),
              Positioned(
                left: 272.0,
                top: 270.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 31.0,
                child: Generated1Widget(),
              ),
              Positioned(
                left: 269.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 31.0,
                child: Generated3Widget(),
              ),
              Positioned(
                left: 30.0,
                top: 253.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 71.0,
                child: GeneratedNumberofHealthyMealsthisweekWidget(),
              ),
              Positioned(
                left: 32.0,
                top: 350.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 71.0,
                child: GeneratedLevelofStressyoufeltthisweek1to10Widget(),
              ),
              Positioned(
                left: 32.0,
                top: 441.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 71.0,
                child: GeneratedScaleof110Widget(),
              ),
              Positioned(
                left: 214.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 25.0,
                child: GeneratedEllipse9Widget1(),
              ),
              Positioned(
                left: 307.0,
                top: 268.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 25.0,
                child: GeneratedEllipse11Widget1(),
              ),
              Positioned(
                left: 307.0,
                top: 364.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 25.0,
                child: GeneratedEllipse12Widget(),
              ),
              Positioned(
                left: 299.0,
                top: 264.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 43.0,
                child: GeneratedWidget2(),
              ),
              Positioned(
                left: 206.0,
                top: 182.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 43.0,
                child: GeneratedWidget3(),
              ),
              Positioned(
                left: 210.0,
                top: 263.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 43.0,
                child: GeneratedWidget4(),
              ),
              Positioned(
                left: 208.0,
                top: 356.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 43.0,
                child: GeneratedWidget5(),
              ),
              Positioned(
                left: 301.0,
                top: 440.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 43.0,
                child: GeneratedWidget6(),
              ),
              Positioned(
                left: 299.0,
                top: 359.0,
                right: null,
                bottom: null,
                width: 49.0,
                height: 43.0,
                child: GeneratedWidget7(),
              ),
              Positioned(
                left: 307.0,
                top: 185.0,
                right: null,
                bottom: null,
                width: 27.0,
                height: 25.0,
                child: GeneratedEllipse10Widget1(),
              ),
              Positioned(
                left: 302.0,
                top: 180.0,
                right: null,
                bottom: null,
                width: 42.0,
                height: 43.0,
                child: GeneratedWidget8(),
              ),
              Positioned(
                left: 115.0,
                top: 519.0,
                right: null,
                bottom: null,
                width: 164.0,
                height: 34.0,
                child: GeneratedButtonWidget4(),
              ),
              Positioned(
                left: 246.5,
                top: 597.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse18Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.042666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 16.0;

                  double percentHeight = 0.019704433497536946;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 16.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.704,
                        translateY: constraints.maxHeight * 0.7536945812807881,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedIconsocialperson_outline_24pxWidget1())
                  ]);
                }),
              ),
              Positioned(
                left: 163.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse19Widget(),
              ),
              Positioned(
                left: 179.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 38.0,
                child: GeneratedWidget9(),
              ),
              Positioned(
                left: 82.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse20Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcontogglestar_outline_24pxWidget2(),
              )
            ]),
      ),
    ));
  }
}
