import 'package:flutter/material.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget1/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget1/generated/GeneratedYoursafespaceduringthepandemicWidget.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget1/generated/GeneratedRectangleWidget10.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget1/generated/GeneratedButtonWidget14.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget1/generated/GeneratedEllipse3Widget1.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget1/generated/GeneratedEllipse2Widget1.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget1/generated/GeneratedImage5Widget.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget1/generated/GeneratedFrame1Widget2.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget1/generated/GeneratedStatusBarWidget6.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget1/generated/GeneratedRectangleWidget9.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget1/generated/GeneratedRectangleWidget8.dart';

/* Frame Intro Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntroPageWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget8(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget9(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget10(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget6(),
              ),
              Positioned(
                left: 81.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 51.0,
                child: GeneratedFrame1Widget2(),
              ),
              Positioned(
                left: 136.0,
                top: 604.0,
                right: 137.0,
                bottom: null,
                width: null,
                height: 40.0,
                child: GeneratedButtonWidget14(),
              ),
              Positioned(
                left: 142.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 182.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse2Widget1(),
              ),
              Positioned(
                left: 222.0,
                top: 574.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse3Widget1(),
              ),
              Positioned(
                left: 78.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 218.0,
                child: GeneratedYoursafespaceduringthepandemicWidget(),
              ),
              Positioned(
                left: 72.0,
                top: 391.0,
                right: null,
                bottom: null,
                width: 230.0,
                height: 183.0,
                child: GeneratedImage5Widget(),
              )
            ]),
      ),
    ));
  }
}
