import 'package:flutter/material.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget/generated/GeneratedFrame1Widget1.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget/generated/GeneratedRectangleWidget5.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget/generated/GeneratedStatusBarWidget5.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget/generated/GeneratedEllipse3Widget.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget/generated/GeneratedButtonWidget13.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget/generated/GeneratedYourguidetodailyselfcareWidget.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget/generated/GeneratedRectangleWidget7.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget/generated/GeneratedImage3Widget.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget/generated/GeneratedRectangleWidget6.dart';
import 'package:flutterapp/machacksapp/generatedintropagewidget/generated/GeneratedEllipse2Widget.dart';

/* Frame Intro Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntroPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget5(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget6(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget7(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget5(),
              ),
              Positioned(
                left: 81.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 51.0,
                child: GeneratedFrame1Widget1(),
              ),
              Positioned(
                left: 78.0,
                top: 73.0,
                right: null,
                bottom: null,
                width: 254.0,
                height: 218.0,
                child: GeneratedYourguidetodailyselfcareWidget(),
              ),
              Positioned(
                left: 137.0,
                top: 601.0,
                right: 136.0,
                bottom: null,
                width: null,
                height: 40.0,
                child: GeneratedButtonWidget13(),
              ),
              Positioned(
                left: 142.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 182.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse2Widget(),
              ),
              Positioned(
                left: 228.0,
                top: 579.0,
                right: null,
                bottom: null,
                width: 11.0,
                height: 11.0,
                child: GeneratedEllipse3Widget(),
              ),
              Positioned(
                left: 91.0,
                top: 351.0,
                right: null,
                bottom: null,
                width: 192.0,
                height: 188.0,
                child: GeneratedImage3Widget(),
              )
            ]),
      ),
    ));
  }
}
