import 'package:flutter/material.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedEnablemymoodtrackerWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedButtonWidget2.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedButtonWidget1.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedEllipseWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedIcontoggletoggle_on_24pxWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedIconmapsplace_24pxWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedEnablehealthydiettrackerWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedIcontoggletoggle_off_24pxWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedStatusBarWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedUnionWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedRectangleWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedIconsocialperson_outline_24pxWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedRectangle24Widget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedJaneSmithWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedRectangle25Widget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedEllipse11Widget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedIcontoggletoggle_off_24pxWidget4.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedEllipse10Widget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedEnablephysicalhealthtrackerWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedIcontoggletoggle_off_24pxWidget2.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedEllipse9Widget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedEnablementalhealthtrackerWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedIcontogglestar_outline_24pxWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedButtonWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedSanfranciscocaWidget.dart';
import 'package:flutterapp/machacksapp/generatedprofilewidget/generated/GeneratedRectangle23Widget.dart';

/* Frame Profile
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedProfileWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget(),
              ),
              Positioned(
                left: 33.0,
                top: 83.0,
                right: null,
                bottom: null,
                width: 128.0,
                height: 128.0,
                child: GeneratedEllipseWidget(),
              ),
              Positioned(
                left: 187.0,
                top: 121.0,
                right: null,
                bottom: null,
                width: 174.0,
                height: 35.0,
                child: GeneratedJaneSmithWidget(),
              ),
              Positioned(
                left: 214.0,
                top: 188.0,
                right: null,
                bottom: null,
                width: 135.0,
                height: 17.0,
                child: GeneratedSanfranciscocaWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 329.0,
                right: null,
                bottom: null,
                width: 243.0,
                height: 17.0,
                child: GeneratedEnablephysicalhealthtrackerWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 386.0,
                right: null,
                bottom: null,
                width: 215.0,
                height: 17.0,
                child: GeneratedEnablehealthydiettrackerWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 443.0,
                right: null,
                bottom: null,
                width: 231.0,
                height: 17.0,
                child: GeneratedEnablementalhealthtrackerWidget(),
              ),
              Positioned(
                left: 18.0,
                top: 506.0,
                right: null,
                bottom: null,
                width: 186.0,
                height: 17.0,
                child: GeneratedEnablemymoodtrackerWidget(),
              ),
              Positioned(
                left: 192.0,
                top: 1130.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 220.0,
                child: GeneratedRectangle25Widget(),
              ),
              Positioned(
                left: 192.0,
                top: 811.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 310.0,
                child: GeneratedRectangle23Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 1040.0,
                right: null,
                bottom: null,
                width: 167.0,
                height: 310.0,
                child: GeneratedRectangle24Widget(),
              ),
              Positioned(
                left: 16.0,
                top: 1382.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedButtonWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget(),
              ),
              Positioned(
                left: 21.0,
                top: 66.0,
                right: null,
                bottom: null,
                width: 12.207107543945312,
                height: 11.353558540344238,
                child: GeneratedUnionWidget(),
              ),
              Positioned(
                left: 13.0,
                top: 246.0,
                right: null,
                bottom: null,
                width: 343.0,
                height: 52.0,
                child: GeneratedButtonWidget1(),
              ),
              Positioned(
                left: 14.0,
                top: 724.0,
                right: null,
                bottom: null,
                width: 63.0,
                height: 52.0,
                child: GeneratedButtonWidget2(),
              ),
              Positioned(
                left: 82.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse9Widget(),
              ),
              Positioned(
                left: 95.0,
                top: 608.0,
                right: null,
                bottom: null,
                width: 24.0,
                height: 24.0,
                child: GeneratedIcontogglestar_outline_24pxWidget(),
              ),
              Positioned(
                left: 163.0,
                top: 597.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse10Widget(),
              ),
              Positioned(
                left: 179.0,
                top: 604.0,
                right: null,
                bottom: null,
                width: 22.0,
                height: 38.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 246.5,
                top: 597.0,
                right: null,
                bottom: null,
                width: 50.0,
                height: 46.0,
                child: GeneratedEllipse11Widget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.037333333333333336;
                  double scaleX = (constraints.maxWidth * percentWidth) / 14.0;

                  double percentHeight = 0.024630541871921183;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 20.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.49333333333333335,
                        translateY: constraints.maxHeight * 0.22536945812807882,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedIconmapsplace_24pxWidget())
                  ]);
                }),
              ),
              Positioned(
                left: 288.0,
                top: 362.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 63.0,
                child: GeneratedIcontoggletoggle_off_24pxWidget(),
              ),
              Positioned(
                left: 287.0,
                top: 419.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 63.0,
                child: GeneratedIcontoggletoggle_off_24pxWidget2(),
              ),
              Positioned(
                left: 288.0,
                top: 305.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 63.0,
                child: GeneratedIcontoggletoggle_off_24pxWidget4(),
              ),
              Positioned(
                left: 286.0,
                top: 484.0,
                right: null,
                bottom: null,
                width: 67.0,
                height: 59.0,
                child: GeneratedIcontoggletoggle_on_24pxWidget(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: 0.0,
                width: null,
                height: null,
                child: LayoutBuilder(builder:
                    (BuildContext context, BoxConstraints constraints) {
                  double percentWidth = 0.042666666666666665;
                  double scaleX = (constraints.maxWidth * percentWidth) / 16.0;

                  double percentHeight = 0.019704433497536946;
                  double scaleY =
                      (constraints.maxHeight * percentHeight) / 16.0;

                  return Stack(children: [
                    TransformHelper.translateAndScale(
                        translateX: constraints.maxWidth * 0.704,
                        translateY: constraints.maxHeight * 0.7536945812807881,
                        translateZ: 0,
                        scaleX: scaleX,
                        scaleY: scaleY,
                        scaleZ: 1,
                        child: GeneratedIconsocialperson_outline_24pxWidget())
                  ]);
                }),
              )
            ]),
      ),
    ));
  }
}
