import 'package:flutter/material.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget3/generated/GeneratedButtonWidget17.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget3/generated/GeneratedUploadprofilepictureWidget.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget3/generated/GeneratedStatusBarWidget10.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget3/generated/GeneratedImage4Widget.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget3/generated/GeneratedRectangleWidget16.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget3/generated/GeneratedFrame1Widget6.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget3/generated/GeneratedEllipse21Widget.dart';
import 'package:flutterapp/machacksapp/generatedloginpagewidget3/generated/GeneratedFinalstepWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 375.0,
        height: 812.0,
        child: Stack(
            fit: StackFit.expand,
            alignment: Alignment.center,
            overflow: Overflow.visible,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: null,
                bottom: null,
                width: 375.0,
                height: 812.0,
                child: GeneratedRectangleWidget16(),
              ),
              Positioned(
                left: 0.0,
                top: 0.0,
                right: 0.0,
                bottom: null,
                width: null,
                height: 44.0,
                child: GeneratedStatusBarWidget10(),
              ),
              Positioned(
                left: 81.0,
                top: 99.0,
                right: null,
                bottom: null,
                width: 246.0,
                height: 51.0,
                child: GeneratedFrame1Widget6(),
              ),
              Positioned(
                left: 43.0,
                top: 150.0,
                right: null,
                bottom: null,
                width: 290.0,
                height: 64.0,
                child: GeneratedFinalstepWidget(),
              ),
              Positioned(
                left: 16.0,
                top: 567.0,
                right: 16.0,
                bottom: null,
                width: null,
                height: 52.0,
                child: GeneratedButtonWidget17(),
              ),
              Positioned(
                left: 126.0,
                top: 284.0,
                right: null,
                bottom: null,
                width: 123.0,
                height: 123.0,
                child: GeneratedEllipse21Widget(),
              ),
              Positioned(
                left: 151.0,
                top: 296.0,
                right: null,
                bottom: null,
                width: 72.0,
                height: 100.0,
                child: GeneratedImage4Widget(),
              ),
              Positioned(
                left: 103.0,
                top: null,
                right: null,
                bottom: null,
                width: 170.0,
                height: 25.0,
                child: TransformHelper.translate(
                    x: 0.00,
                    y: 44.50,
                    z: 0,
                    child: GeneratedUploadprofilepictureWidget()),
              )
            ]),
      ),
    ));
  }
}
